jira:
  sprint:
    boardName: "YOUR_PROJECT"

  url: https://your-jira-instance.com
  token: "${HEXA_JIRA_TOKEN}" # Set your JIRA_TOKEN environment variable
  user: 
    email: "${HEXA_JIRA_USER_EMAIL}"


slack:
  webhook_url: "${SLACK_WEBHOOK_URL}"

user:
  email: "${HEXA_USER_EMAIL}"
