name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip release')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Calculate next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create and push tag
        if: steps.semver.outputs.bump != 'none'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Version bump: ${{ steps.semver.outputs.bump }}"
          echo "Current version: ${{ steps.semver.outputs.current }}"
          echo "Next version: ${{ steps.semver.outputs.next }}"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.semver.outputs.next }}
          git push origin ${{ steps.semver.outputs.next }}

      - name: Skip release
        if: steps.semver.outputs.bump == 'none'
        run: |
          echo "No version bump needed - skipping release"
          echo "Current version: ${{ steps.semver.outputs.current }}"
          echo "Latest commits do not require a new release"

      - name: Run GoReleaser
        if: steps.semver.outputs.bump != 'none'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.semver.outputs.next }}